
name: Static Analysis (Linting, License, Type checks...)

on:
    pull_request_target:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    check:
        name: All
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request_target' }}

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  fetch-depth: 0

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate. This also
              # helps to catch dependencies not being installed with exact version.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              # See: https://github.com/WordPress/gutenberg/pull/39865
              run: npm install

            - name: Debug github.head_ref
              run: | 
                echo ${{ github.head_ref }}
                echo ${{ github.ref }}
                echo ${{ github.event.pull_request.head.ref }}
                echo ${{ github.event.pull_request.base.ref }}
                
            - name: Configure git user name and email
              run: |
                  git config user.name "Gutenberg Repository Automation"
                  git config user.email bangank36@gmail.com
            - name: Rebuild docs manifest
              run: |
                git checkout ${{ github.head_ref }}
                npm run docs:build
                git add docs/manifest.json
                git commit -m "Update docs manifests" --no-verify
                git push origin ${{ github.head_ref }}
            - name: Setup tmate session After Docs rebuild
              if: failure()
              uses: mxschmitt/action-tmate@v3

            - name: Lint JavaScript and Styles
              run: npm run lint

            - name: Type checking
              run: npm run build:package-types

            - name: Check local changes
              run: npm run other:check-local-changes

            - name: License compatibility
              run: npm run other:check-licenses